version: '3.8'

services:
  database:
    image: mysql:8
    container_name: signator_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: signator
      MYSQL_PASSWORD: ib4psqegbQHdSS7k
      MYSQL_DATABASE: signator
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    container_name: signator_app
    build:
      context: .
    environment:
      NODE_ENV: development
      DATABASE_URL: "mysql://signator:ib4psqegbQHdSS7k@database:3306/signator"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "Db3mwtDhQFwh/2UAPMzeMsgrhZ3XRkfiH4JoDOkj1a0="
      AUTH_SECRET: "Db3mwtDhQFwh/2UAPMzeMsgrhZ3XRkfiH4JoDOkj1a0="
      OPENAI_API_KEY: "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"
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    develop:
      watch:
        - action: sync
          path: ./app
          target: /src/app
          ignore:
            - .git
            - node_modules
        - action: rebuild
          path: package.json

volumes:
  mysql_data: